package net.swordie.ms.constants;

/**
 * @author Sjonnie
 * Created on 8/19/2018.
 */
public class QuestConstants {
    public static final int MONSTER_BOOK = 1047;
    public static final int SAVE_EXP_BUFF = 1062;
    public static final int WEDDING_DIVORCE = 1103;
    public static final int QR_WeddingVows30days = 1125;
    public static final int QR_WeddingVows100days = 1126;
    public static final int QR_RecommendPartyQuestSave = 1216;
    public static final int QR_MonsterCarnival = 1301;
    public static final int QR_MonsterCarnivalS2 = 1302;
    public static final int BEAST_FORM_WING_ON_OFF = 1544;
    public static final int QR_CrossHunterUI_Alert = 1652;
    public static final int QR_MysticFieldTuto = 1676;
    public static final int QR_MysticFieldReward = 1683;

    public static final int QR_MysticFieldTrasferCheck = 1685;
    public static final int QR_MysticFieldTuto_Reopen = 1693;
    public static final int QR_EvolvingSystemTutorial = 1807;
    public static final int QR_EvolvingSystemDayLimit = 1817;
    public static final int QR_EvolvingSystemMedal_Quest = 1841;
    public static final int QR_EvolvingSystemMedal_Record = 1842;
    public static final int QR_MakingTutorial = 2550;


    public static final int QR_AdventureJournal_Start_Dual = 2646;
    public static final int QR_LionKing = 3162;
    public static final int QR_DojangRankBest = 3850;
    public static final int QR_DojangMindBodyTraining = 3851;
    public static final int QR_DojangRankInfo = 3852;
    public static final int QR_Aswan_Clear_Easy = 3970;
    public static final int QR_Aswan_Clear_Normal = 3971;
    public static final int QR_Hillah_Achievement = 3990;
    public static final int QR_Circulator_Gift = 3994;
    public static final int QR_Circulator_Quest = 3995;
    public static final int QR_CharmPocket_SlotOpen = 6500;
    public static final int QR_Tutorial_PirateBless = 6600;
    public static final int QR_Tutorial_ElfsReturn = 6601;
    public static final int QR_Tutorial_DemonsFury = 6602;
    public static final int QR_Tutorial_DeadlyInstinct = 6606;
    public static final int QR_Tutorial_MichaelStance = 6607;
    public static final int QR_Tutorial_LightmagePermeate = 6608;
    public static final int QR_Tutorial_KaiserStrongStamina = 6609;


    public static final int QR_Tutorial_DragonPirateSoulRage = 0x19D2;
    public static final int QR_Tutorial_XenonAggressiveLogic = 0x19D3;
    public static final int QR_Tutorial_DavangerWildRage = 0x19D4;
    public static final int QR_Tutorial_CygnusBless = 0x19D5;
    public static final int QR_Tutorial_HiddenExcapeDeath = 0x19D6;
    public static final int QR_ZakumDungeon = 0x1B58;
    public static final int QR_AswanEnter = 0x1B7A;
    public static final int QR_AswanCoin_History = 0x1B7B;
    public static final int QR_Circulator_Data = 0x1B7C;


    public static final int QR_Dojang_Ranking_Reward = 0x1C2C;
    public static final int QR_DailyCallenge_Dojang = 0x1C30;
    public static final int QR_Balrog_Clear = 0x1C36;
    public static final int QR_Defense_Wave = 0x1C48;
    public static final int QR_Defense_Life = 0x1C49;
    public static final int QR_DailyCallenge_Pyramid = 0x1C4A;
    public static final int QR_SkillSPReset_2012_SUMMER = 0x1C51;
    public static final int QR_Dojang_JobRanking = 0x1C60;
    public static final int QR_BossWaitlinesReturnMap = 0x1C61;
    /*
FFFFFFFF QR_BossWaitlinesReturnMap  = 1C61h
FFFFFFFF QR_Tower_Chair_Info  = 1C62h
FFFFFFFF QR_Dojang_ClearPoint  = 1C71h
FFFFFFFF QR_Dojang_UserPoint  = 1C72h
FFFFFFFF QR_ActiveNickName  = 1C7Ah
FFFFFFFF QR_ActiveDamageSkin  = 1C7Bh
FFFFFFFF QR_ActiveCustomizeEffect  = 1C7Ch
FFFFFFFF QR_AriantArenaResult  = 1CA6h
FFFFFFFF QR_AriantArenaPlayTime  = 1CA7h
FFFFFFFF QR_MonsterCarnivalS2_BP  = 1D88h
FFFFFFFF QR_MonsterCarnivalS2_OurTotalCP  = 1D8Ah
FFFFFFFF QR_MonsterCarnivalS2_OpponentTotalCP  = 1D8Bh
FFFFFFFF QR_MonsterCarnivalS2_ElaspedTime  = 1D8Ch
FFFFFFFF QR_MonsterCarnivalS2_WinCount  = 1D8Dh
FFFFFFFF QR_MonsterCarnivalS2_LoseCount  = 1D8Eh
FFFFFFFF QR_MonsterCarnivalS2_DrawCount  = 1D8Fh
FFFFFFFF QR_MateSupportedPhone  = 1DB1h
FFFFFFFF QR_MatePhoneNumber  = 1DB2h
FFFFFFFF QR_WeddingVillage  = 1DBAh
FFFFFFFF QR_WeddingType   = 1DBCh
FFFFFFFF QR_WeddingDay    = 1DBEh
FFFFFFFF QR_WeddingStatus  = 1DC0h
FFFFFFFF QR_2012Battle_RPSGame  = 1E1Ch
FFFFFFFF QR_Massacre_TotalHitCount  = 1E50h
FFFFFFFF QR_Massacre_Clear  = 1E51h
FFFFFFFF QR_SettingSonOfLinkedSkill  = 1E67h
FFFFFFFF QR_ElfEarRecord  = 1E68h
FFFFFFFF QR_InnerAbillityInsurance  = 1E69h
FFFFFFFF QR_EventStamp    = 1E6Eh
FFFFFFFF QR_MECHANIC_HUEVALUE  = 1E91h
FFFFFFFF QR_BuyEquipExt   = 1E96h
FFFFFFFF QR_MakingMapTransfer  = 1EB4h
FFFFFFFF QR_PvPMode_LastRoomOut  = 1EC9h
FFFFFFFF QR_PvP_HardCore_WinLose  = 1ECAh
FFFFFFFF QR_PvP_HardCore_Result  = 1ECBh
FFFFFFFF QR_CharmPocket_SlotOpen2  = 1ECCh
FFFFFFFF QR_PvP_HardCore_Nickname  = 1ECDh
FFFFFFFF QR_PvP_HardCore_Gladiator  = 1ECEh
FFFFFFFF QR_WU_Moonrabbit  = 1EE1h
FFFFFFFF QR_WU_Quest_enter  = 1EE2h
FFFFFFFF QR_PartyQuestPoint  = 1EE3h
FFFFFFFF QR_DailyCallenge_Aswan  = 1F1Bh
FFFFFFFF QR_Hyper_Skill_Record_Cost_Money  = 1F1Dh
FFFFFFFF QR_SkillUIHelperPopup  = 1F1Eh
FFFFFFFF QR_ExpPlusEventAccountRecord  = 1F2Ch
FFFFFFFF QR_ExpPlusEventProgress  = 1F2Dh
FFFFFFFF QR_ExpPlusEventPushItemInfo  = 1F2Eh
FFFFFFFF QR_ExpPlusEventFlowInfo  = 1F2Fh
FFFFFFFF QR_ExpPlusItemBackUp  = 1F31h
FFFFFFFF QR_Rune_Use_Date  = 1F3Ah
FFFFFFFF QR_MacroDetect   = 1F3Bh
FFFFFFFF QR_MacroDetectEx  = 1F3Ch
FFFFFFFF QR_RPSGame       = 2508h
FFFFFFFF QR_Plant         = 2694h
FFFFFFFF QR_AdminShop     = 27D9h
FFFFFFFF QR_AdminShopItemRegister  = 27DCh
FFFFFFFF QR_CookieHouse_MaxPoint  = 27F2h
FFFFFFFF QR_CookieHouse_LastPoint  = 27F3h
FFFFFFFF QR_MaxCombo      = 285Fh
FFFFFFFF QR_PremiumUserQuest_Base  = 29A5h
FFFFFFFF QR_2010FallMoon  = 2A7Ch
FFFFFFFF QR_BoomUpEvent_Character_Begin  = 2ABCh
FFFFFFFF QR_BoomUpEvent_Character_End  = 2ABEh
FFFFFFFF QR_PvPMode_Score  = 2B0Ch
FFFFFFFF QR_PvPMode_TeamDeath_Win_Count  = 2B0Dh
FFFFFFFF QR_PvPMode_IceKnight_Win_Count_For_IceKnight  = 2B0Eh
FFFFFFFF QR_PvPMode_IceKnight_Score  = 2B10h
FFFFFFFF QR_PvPMode_IceKnight_Win_Count_For_Challenger  = 2B11h
FFFFFFFF QR_PvPMode_TeamDeath_Win_Count_Daily  = 2B12h
FFFFFFFF QR_PvPMode_DeathMatch_Score  = 2B13h
FFFFFFFF QR_PvPMode_Participate_Count  = 2B14h
FFFFFFFF QR_PvPMode_IceKnight_Win_Count_Daily  = 2B15h
FFFFFFFF QR_EliminationOfBigMoonRabbit  = 2B16h
FFFFFFFF QR_PvPMode_IceKnight_Score_Quest1  = 2B27h
FFFFFFFF QR_PvPMode_IceKnight_Score_Quest2  = 2B28h
FFFFFFFF QR_PvPMode_IceKnight_Morph_Quest  = 2B29h
FFFFFFFF QR_PvPMode_IceKnight_Morph_Check  = 2B2Ah
FFFFFFFF QR_JumpEvent_NewCharacter  = 2C47h
FFFFFFFF QR_JumpEvent_NewCharacter_JobChange  = 2C49h
FFFFFFFF QR_PrizeEvent    = 2CB4h
FFFFFFFF QR_PvPMode_BoomUpEvent_Check1  = 2D28h
FFFFFFFF QR_PvPMode_BoomUpEvent_PvPPoint  = 2D29h
FFFFFFFF QR_PvPMode_BoomUpEvent_Check2  = 2D2Bh
FFFFFFFF QR_PvPMode_BoomUpEvent_Check3  = 2D2Ch
FFFFFFFF QR_PvP_OneDay_MAX_Battle_Point  = 2D2Dh
FFFFFFFF QR_Macro_Exp_Decresase_Check  = 2D64h
FFFFFFFF QR_LittleIndian  = 2E40h
FFFFFFFF QR_FallSportsDay_BakCrash  = 2E5Ch
FFFFFFFF QR_FallSportsDay_JulDarigi  = 2E5Fh
FFFFFFFF QR_RelaxEXP_Time  = 2E90h
FFFFFFFF QR_Halloween_Candy  = 2E9Ah
FFFFFFFF QR_LevelUpGuideNotice  = 2F27h
FFFFFFFF QR_NewyearBlackDragon  = 2F3Ch
FFFFFFFF QR_EVENTSKILL_USED_COUNT_INADAY  = 2FDBh
FFFFFFFF QR_EVENTSKILL_LAST_USED_DAY  = 2FDCh
FFFFFFFF QR_SamSamSamEvent_MobCount  = 2FE9h
FFFFFFFF QR_KeyOfLiberation0  = 300Ch
FFFFFFFF QR_KeyOfLiberation1  = 300Dh
FFFFFFFF QR_KeyOfLiberation2  = 300Eh
FFFFFFFF QR_KeyOfLiberation3  = 300Fh
FFFFFFFF QR_KeyOfLiberation4  = 3010h
FFFFFFFF QR_KeyOfLiberation5  = 3011h
FFFFFFFF QR_KeyOfLiberation6  = 3012h
FFFFFFFF QR_KeyOfLiberation7  = 3013h
FFFFFFFF QR_KeyOfLiberation8  = 3014h
FFFFFFFF QR_KeyOfLiberation9  = 3015h
FFFFFFFF QR_KeyOfLiberation10  = 3016h
FFFFFFFF QR_KeyOfLiberation11  = 3017h
FFFFFFFF QR_KeyOfLiberation12  = 3018h
FFFFFFFF QR_KeyOfLiberation13  = 3019h
FFFFFFFF QR_KeyOfLiberation14  = 301Ah
FFFFFFFF QR_KeyOfLiberation15  = 301Bh
FFFFFFFF QR_KeyOfLiberation16  = 301Ch
FFFFFFFF QR_KeyOfLiberation17  = 301Dh
FFFFFFFF QR_KeyOfLiberation18  = 301Eh
FFFFFFFF QR_KeyOfLiberation19  = 301Fh
FFFFFFFF QR_KeyOfLiberation20  = 3020h
FFFFFFFF QR_WeddingExStatus  = 3026h
FFFFFFFF QR_BossShieldCoolTime  = 302Ah
FFFFFFFF QR_PetSkillSetting  = 302Eh
FFFFFFFF QR_ValuePack_Info  = 303Ch
FFFFFFFF QR_MapleStyle    = 3047h
FFFFFFFF QR_MapleStyle_Bonus  = 3048h
FFFFFFFF QR_PremiumUserQuest_Reward1  = 3055h
FFFFFFFF QR_Character_Potential_Cash_Cube_Use  = 3069h
FFFFFFFF QR_Character_Potential_Get_Cube  = 306Dh
FFFFFFFF QR_BoardGame_Info  = 30D5h
FFFFFFFF QR_Bingo_Deck    = 30DDh
FFFFFFFF QR_Bingo_Info    = 30DEh
FFFFFFFF QR_Bingo_Start   = 30DFh
FFFFFFFF QR_PvP_HardCore_Event  = 3158h
FFFFFFFF QR_PvP_HardCore_Event_1  = 3159h
FFFFFFFF QR_PvP_HardCore_Event_2  = 315Ah
FFFFFFFF QR_PvP_HardCore_Event_3  = 315Bh
FFFFFFFF QR_PvP_HardCore_Event_Check  = 315Ch
FFFFFFFF QR_MesoRanger    = 3192h
FFFFFFFF QR_MesoRanger_Start  = 3193h
FFFFFFFF QR_KaiserColorOrMorphChange  = 323Ch
FFFFFFFF QR_BoardGame_Start  = 3260h
FFFFFFFF QR_MapleSchool_Start  = 3273h
FFFFFFFF QR_MapleSchool_Chapter1  = 3274h
FFFFFFFF QR_MapleSchool_Chapter2  = 3276h
FFFFFFFF QR_MapleSchool_Chapter3  = 3278h
FFFFFFFF QR_MapleSchool_Chapter4  = 327Ah
FFFFFFFF QR_MapleSchool_Chapter5  = 327Ch
FFFFFFFF QR_MapleSchool_Chapter6  = 327Eh
FFFFFFFF QR_MapleSchool_Chapter7  = 3280h
FFFFFFFF QR_MapleSchool_ClearCount  = 3283h
FFFFFFFF QR_MapleSchool_Event  = 3286h
FFFFFFFF QR_Event_MapleMuseumUI  = 3287h
FFFFFFFF QR_Event_MapleMuseum  = 3288h
FFFFFFFF QR_Event_MuseumKing_1  = 3289h
FFFFFFFF QR_Event_MuseumKing_2  = 328Ah
FFFFFFFF QR_Event_MuseumKing_3  = 328Bh
FFFFFFFF QR_Event_MapleMuseumReset  = 328Ch
FFFFFFFF QR_YutGame_Info_2012  = 32A0h
FFFFFFFF QR_YutGame_Info_2012_History  = 32A1h
FFFFFFFF QR_YutGame_Achivement_2012  = 32A2h
FFFFFFFF QR_YutGame_Start_2012  = 32A3h
FFFFFFFF QR_2012Fall_Weave  = 32BBh
FFFFFFFF QR_2012Fall_SportsDay_TugOfWar  = 32CBh
FFFFFFFF QR_2012Fall_SportsDay_GourdCrash  = 32CDh
FFFFFFFF QR_2012HalloweenCandy  = 32EBh
FFFFFFFF QR_2012HalloweenCandyReward  = 32ECh
FFFFFFFF QR_ActionHero    = 32EDh
FFFFFFFF QR_2012HalloweenAnnocement  = 32F2h
FFFFFFFF QR_Indian_Achivement_2012  = 3368h
FFFFFFFF QR_ActionHero2   = 3376h
FFFFFFFF QR_SaveDamageSkinInfo  = 3386h
FFFFFFFF QR_SaveDamageSkinList  = 3387h
FFFFFFFF QR_Action_Achivement_2012  = 33A9h
FFFFFFFF QR_Winter2012_Achievement  = 33E0h
FFFFFFFF QR_Attendance    = 33FDh
FFFFFFFF QR_Event_Lottery_Reward_Mon_1  = 3402h
FFFFFFFF QR_Event_Lottery_Reward_Mon_2  = 3403h
FFFFFFFF QR_Event_Lottery_Reward_Mon_3  = 3404h
FFFFFFFF QR_Event_Lottery_Reward_Tue_1  = 3405h
FFFFFFFF QR_Event_Lottery_Reward_Tue_2  = 3406h
FFFFFFFF QR_Event_Lottery_Reward_Tue_3  = 3407h
FFFFFFFF QR_Event_Lottery_Reward_Wed_1  = 3408h
FFFFFFFF QR_Event_Lottery_Reward_Wed_2  = 3409h
FFFFFFFF QR_Event_Lottery_Reward_Wed_3  = 340Ah
FFFFFFFF QR_Event_Lottery_Reward_Thu_1  = 340Bh
FFFFFFFF QR_Event_Lottery_Reward_Thu_2  = 340Ch
FFFFFFFF QR_Event_Lottery_Reward_Thu_3  = 340Dh
FFFFFFFF QR_Event_Lottery_Reward_Fri_1  = 340Eh
FFFFFFFF QR_Event_Lottery_Reward_Fri_2  = 340Fh
FFFFFFFF QR_Event_Lottery_Reward_Fri_3  = 3410h
FFFFFFFF QR_Event_Lottery_Reward_Sat_1  = 3411h
FFFFFFFF QR_Event_Lottery_Reward_Sat_2  = 3412h
FFFFFFFF QR_Event_Lottery_Reward_Sat_3  = 3413h
FFFFFFFF QR_Event_Lottery_Reward_Sun_1  = 3414h
FFFFFFFF QR_Event_Lottery_Reward_Sun_2  = 3415h
FFFFFFFF QR_Event_Lottery_Reward_Sun_3  = 3416h
FFFFFFFF QR_Event_Lottery_Reward_NextMon_1  = 3417h
FFFFFFFF QR_Event_Lottery_Reward_NextMon_2  = 3418h
FFFFFFFF QR_Event_Lottery_Reward_NextMon_3  = 3419h
FFFFFFFF QR_Event_Lottery_Mon  = 341Ah
FFFFFFFF QR_Event_Lottery_Tue  = 341Bh
FFFFFFFF QR_Event_Lottery_Wed  = 341Ch
FFFFFFFF QR_Event_Lottery_Thu  = 341Dh
FFFFFFFF QR_Event_Lottery_Fri  = 341Eh
FFFFFFFF QR_Event_Lottery_Sat  = 341Fh
FFFFFFFF QR_Event_Lottery_Sun  = 3420h
FFFFFFFF QR_Event_Lottery_MonNext  = 3421h
FFFFFFFF QR_Roulette_Roll_Count  = 3442h
FFFFFFFF QR_Winter2012_Achievement_Start  = 34BCh
FFFFFFFF QR_BingoCassandra_Deck  = 34C0h
FFFFFFFF QR_BingoCassandra_Info  = 34C1h
FFFFFFFF QR_BingoCassandra_Start  = 34C2h
FFFFFFFF QR_GilSsam       = 34CEh
FFFFFFFF QR_MultiYutGiveUp  = 34D5h
FFFFFFFF QR_BigRabbit     = 350Bh
FFFFFFFF QR_Event_MuseumKingS2_1  = 3551h
FFFFFFFF QR_Event_MuseumKingS2_2  = 3552h
FFFFFFFF QR_Event_MuseumKingS2_3  = 3553h
FFFFFFFF QR_Event_MuseumKingS2_Reward_1  = 3554h
FFFFFFFF QR_Event_MuseumKingS2_RewardRecord  = 3555h
FFFFFFFF QR_Event_MuseumKingS2_Reward_2  = 3557h
FFFFFFFF QR_Event_MuseumKingS2_Reward_3  = 3558h
FFFFFFFF QR_Event_MuseumKingS2_ChangeItem_1  = 3559h
FFFFFFFF QR_Event_MuseumKingS2_ChangeItem_2  = 355Ah
FFFFFFFF QR_Event_MuseumKingS2_ChangeItem_3  = 355Bh
FFFFFFFF QR_Maple10Ago    = 35C0h
FFFFFFFF QR_TenthAnniGiveUp  = 35D7h
FFFFFFFF QR_TenthAnniFirst  = 35F0h
FFFFFFFF QR_MapleGift     = 361Ah
FFFFFFFF QR_MapleMiniParty_Invite  = 363Dh
FFFFFFFF QR_MiniParty_Reward  = 3640h
FFFFFFFF QR_Event_Name_Tag  = 364Eh
FFFFFFFF QR_BattleField_Invite  = 3665h
FFFFFFFF QR_BattleField_Medal  = 3667h
FFFFFFFF QR_BattleField_Reward  = 3668h
FFFFFFFF QR_RhythmGame_Invite  = 36C9h
FFFFFFFF QR_MiniGame_SpaceMoonRabbit  = 3770h
FFFFFFFF QR_MiniGame_Catapult  = 3778h
FFFFFFFF QR_Catapult_Reward  = 377Bh
FFFFFFFF QR_2013_Chuseok_Coin_Record_1st  = 3794h
FFFFFFFF QR_2013_Chuseok_Coin_Record_2nd  = 3795h
FFFFFFFF QR_2013_Halloween_Gamsper_Info  = 37A3h
FFFFFFFF QR_2013_Halloween_Gamsper_MissionA  = 37A5h
FFFFFFFF QR_2013_Capture_Flag  = 37B9h
FFFFFFFF QR_WORLD_TRANSFER_RECORD  = 37C8h
FFFFFFFF QR_GroupInvitationSaveMap  = 37CBh
FFFFFFFF QR_HundredBingoReward  = 37CCh
FFFFFFFF QR_2013_Capture_Flag2  = 37CEh
FFFFFFFF QR_2013_Capture_Flag3  = 37CFh
FFFFFFFF QR_WORLD_TRANSFER_RECORD_2ND  = 37D0h
FFFFFFFF QR_YnIFestival_GiveUp  = 37D2h
FFFFFFFF QR_OmokRenew_Cur  = 37DFh
FFFFFFFF QR_MemoryGame_2013_Result  = 37E3h
FFFFFFFF QR_TABG_Result   = 37EBh
FFFFFFFF QR_MYG_Result    = 37EFh
FFFFFFFF QR_OmokRenew_Record  = 37F3h
FFFFFFFF QR_MemoryGame_2013_Recode  = 37F4h
FFFFFFFF QR_WORLD_TRANSFER_RECORD_2015  = 380Ah
FFFFFFFF QR_WORLD_TRANSFER_RECORD_2015_2ND  = 380Bh
FFFFFFFF QR_WORLD_TRANSFER_RECORDEX  = 3814h
FFFFFFFF QR_TypingGameRecode  = 3828h
FFFFFFFF QR_TypingGameMode  = 3829h
FFFFFFFF QR_HundredOxQuizRecode  = 382Fh
FFFFFFFF QR_2014_event_butterfly  = 384Ah
FFFFFFFF QR_Event_ForceAtom  = 3851h
FFFFFFFF QR_Event_Name_Tag_2  = 3899h
FFFFFFFF QR_BattleField_2015_Invite  = 3932h
FFFFFFFF QR_BattleField_2015_Medal  = 3934h
FFFFFFFF QR_BattleField_2015_Result  = 3935h
FFFFFFFF QR_DorajiPotRecord  = 39A3h
FFFFFFFF QR_PlantPotRecord1  = 39A4h
FFFFFFFF QR_DorajiPotResult  = 39A7h
FFFFFFFF QR_12TH_TRESURE  = 39AAh
FFFFFFFF QR_12TH_TRESURE_RANK  = 39AFh
FFFFFFFF QR_DorajiPotRecord2  = 39B7h
FFFFFFFF QR_MosterStory_2015_04_Episode  = 39D1h
FFFFFFFF QR_Secret_Diary_Rinforce  = 3A45h
FFFFFFFF QR_BingsooUpdateCheck  = 3A5Bh
FFFFFFFF QR_PremiumUserQuest_Reward2  = 3A62h
FFFFFFFF QR_PremiumUserQuest_Reward3  = 3A63h
FFFFFFFF QR_PremiumUserQuest_Reward4  = 3A64h
FFFFFFFF QR_ToadsHammer_Tutorial  = 3A66h
FFFFFFFF QR_ToadsHammer_Help  = 3A67h
FFFFFFFF QR_HotTimeAbnormal  = 3A6Fh
FFFFFFFF QR_CowGame_Result  = 3A92h
FFFFFFFF QR_RP_CHARACTER_INDEX  = 3AA0h
FFFFFFFF QR_RP_Sengoku_15017  = 3AA9h
FFFFFFFF QR_RP_Sengoku_15018  = 3AAAh
FFFFFFFF QR_RP_Sengoku_15019  = 3AABh
FFFFFFFF QR_RP_Sengoku_15020  = 3AACh
FFFFFFFF QR_RP_Sengoku_15021  = 3AADh
FFFFFFFF QR_Chuseok_2015_Rabbit_Invite  = 3AD3h
FFFFFFFF QR_Chuseok_2015_Mouse_Invite  = 3ADBh
FFFFFFFF QR_PoloFrito_EagleHunting  = 3B25h
FFFFFFFF QR_PoloFrito_CourtshipDance  = 3B27h
FFFFFFFF QR_Halloween_2015_ActionHero_Invite  = 3B2Eh
FFFFFFFF QR_PoloFrito_FlameWolf_Dead  = 3B44h
FFFFFFFF QR_NewYearEventGuide  = 3BB5h
FFFFFFFF QR_TradeKing_NPC_ItemInfo_Reset1  = 3BD5h
FFFFFFFF QR_TradeKing_NPC_ItemInfo_Reset2  = 3BD6h
FFFFFFFF QR_TradeKing_NPC_ItemInfo_Reset3  = 3BD7h
FFFFFFFF QR_TradeKing_NPC_ItemInfo_Reset4  = 3BD8h
FFFFFFFF QR_TradeKing_Item1  = 3BD9h
FFFFFFFF QR_TradeKing_Item2  = 3BDAh
FFFFFFFF QR_TradeKing_Item3  = 3BDBh
FFFFFFFF QR_TradeKing_Coin  = 3BDCh
FFFFFFFF QR_TradeKing_Porter  = 3BDDh
FFFFFFFF QR_TradeKing_Riding  = 3BDEh
FFFFFFFF QR_WORLD_TRANSFER_RECORD_2016  = 3BEDh
FFFFFFFF QR_SaveDamageSkinBlockServerValue  = 3BF9h
FFFFFFFF QR_2016_NewYear_Sign_Event  = 3C18h
FFFFFFFF QR_StarEventRecord  = 3C32h
FFFFFFFF QR_MonsterBattle_Tutorial_QuickSlot  = 43A9h
FFFFFFFF QR_MonsterBattle_Tutorial_Capture  = 43ABh
FFFFFFFF QR_MonsterBattle_Tutorial_Wear_Equip  = 43AEh
FFFFFFFF QR_MonsterBattle_Tutorial_Reg_Skill  = 43AFh
FFFFFFFF QR_MonsterBattle_Tutorial_LevelUp  = 43B0h
FFFFFFFF QR_MonsterBattle_Tutorial_First_Battle  = 43B1h
FFFFFFFF QR_MonsterBattle_Tutorial_Ranking_UI_Open  = 43B2h
FFFFFFFF QR_MonsterBattle_Tutorial_QuickSlot_Ret  = 43B4h
FFFFFFFF QR_MonsterBattle_Tutorial_Capture_Ret  = 43B5h
FFFFFFFF QR_MonsterBattle_Tutorial_Wear_Equip_Ret  = 43B8h
FFFFFFFF QR_MonsterBattle_Tutorial_Reg_Skill_Ret  = 43B9h
FFFFFFFF QR_MonsterBattle_Tutorial_LevelUp_Ret  = 43BAh
FFFFFFFF QR_MonsterBattle_Tutorial_First_Battle_Ret  = 43BBh
FFFFFFFF QR_MonsterBattle_Tutorial_Ranking_UI_Open_Ret  = 43BCh
FFFFFFFF QR_CharSlotIncItemEvent_Count  = 4651h
FFFFFFFF QR_RelaxEXP_Account  = 4654h
FFFFFFFF QR_RenameCharacterEventItem_1  = 466Ah
FFFFFFFF QR_RenameCharacterEventItem_2  = 466Bh
FFFFFFFF QR_RenameCharacterEventItem_3  = 4686h
FFFFFFFF QR_IncubatorHotBonus  = 46BFh
FFFFFFFF QR_Maple10SignEvent  = 46CFh
FFFFFFFF QR_Cashshop_Vip  = 46E2h
FFFFFFFF QR_CashShop_Amount  = 46EBh
FFFFFFFF QR_Auction_Search  = 46FAh
FFFFFFFF QR_CashMileage_Charge  = 4710h
FFFFFFFF QR_Auction_Register  = 4713h
FFFFFFFF QR_Auction_Success  = 4714h
FFFFFFFF QR_Auction_Premium  = 471Ah
FFFFFFFF QR_RenameCharacterEventItem_4  = 472Eh
FFFFFFFF QR_2013_Chuseok_Sign_Event  = 4740h
FFFFFFFF QR_CoordinationContest_AccInfo  = 474Fh
FFFFFFFF QR_CoordinationContest_AccVote  = 4751h
FFFFFFFF QR_CoordinationContest_AccInfo2  = 477Fh
FFFFFFFF QR_UserResearch  = 4796h
FFFFFFFF QR_StarPlanet_AttendanceAccount  = 47BBh
FFFFFFFF QR_CashMileage_Charge2  = 47BCh
FFFFFFFF QR_StarPlanet_AttendanceRestore  = 47C1h
FFFFFFFF QR_FreezeAndHotEvent  = 47F0h
FFFFFFFF QR_Contents_Stamp_Book_Guild  = 47F2h
FFFFFFFF QR_Contents_Stamp_Book_Reinforce  = 47F4h
FFFFFFFF QR_Contents_Stamp_Hub2  = 47F5h
FFFFFFFF QR_Contents_Stamp_Hub  = 47FAh
FFFFFFFF QR_Contents_Stamp_Book_Reward  = 47FBh
FFFFFFFF QR_EventBestFriend  = 47FCh
FFFFFFFF QR_MesoExchange_TradedCount  = 47FFh
FFFFFFFF QR_RenameCharacterEventItem_5  = 4840h
FFFFFFFF QR_MosterStory_2015_04  = 4842h
FFFFFFFF QR_URUS_ENTER    = 48FBh
FFFFFFFF QR_Soul_Party_Dungeon_InterCount  = 4900h
FFFFFFFF QR_CashMileage_Earned_By_SPM_Charge  = 490Ch
FFFFFFFF QR_SPM_Attendance_Account  = 490Dh
FFFFFFFF QR_MonsterCollection_Record  = 4985h
FFFFFFFF QR_PlatformerStage_TryInfo  = 4996h
FFFFFFFF QR_PlatformerStage_Record_Bronze  = 49BAh
FFFFFFFF QR_PlatformerStage_Record_Silver  = 49BBh
FFFFFFFF QR_PlatformerStage_Record_Gold  = 49BCh
FFFFFFFF QR_PlatformerStage_EventInfo  = 49C4h
FFFFFFFF QR_ActiveNickSkillTimeLimited  = 4A4Bh
FFFFFFFF QR_Cygnus_Rebirth_Ereb  = 51DAh
FFFFFFFF QR_AranTutorial  = 5209h
FFFFFFFF QR_AranCommand_State  = 550Ah
FFFFFFFF QR_Evan_Incubator  = 55F7h
FFFFFFFF QR_Evan_No_Egg   = 55FBh
FFFFFFFF QR_Evan_Glove    = 55FCh
FFFFFFFF QR_Evan_Promoted  = 5672h
FFFFFFFF QR_Evan_Riding   = 5782h
FFFFFFFF QR_WildHunter_Jaguar  = 59E0h
FFFFFFFF QR_FromFieldToPhantomShip  = 61B2h
FFFFFFFF QR_Light_Mage_Tutorial1  = 639Ch
FFFFFFFF QR_Light_Mage_Tutorial2  = 639Dh
FFFFFFFF QR_Light_Mage_Tutorial_Count  = 639Eh
FFFFFFFF QR_kaiser_Tutorial_Count  = 6464h
FFFFFFFF QR_Kaiser_Tutorial1  = 647Ah
FFFFFFFF QR_kaiser_Tutorial2  = 647Bh
FFFFFFFF QR_kaiser_Tutorial3  = 647Ch
FFFFFFFF QR_AngelicBurster_SoulRecharge_Tutorial  = 64EDh
FFFFFFFF QR_AngelicBurster_SoulRecharge_Tutorial_Count  = 64EEh
FFFFFFFF QR_JobSwap_Cost  = 655Ah
FFFFFFFF QR_MakingSkill   = 655Ch
FFFFFFFF QR_JobSwap_LastDay  = 6565h
FFFFFFFF QR_BossArenaTotalInfo  = 6568h
FFFFFFFF QR_BossArenaRecentlyPlayInfo  = 6569h
FFFFFFFF QR_BossArenaEtcInfo  = 656Ah
FFFFFFFF QR_BossArenaTodayInfo  = 656Bh
FFFFFFFF QR_EliteMonsterCount  = 656Dh
FFFFFFFF QR_HyperUpgradeHelp  = 6570h
FFFFFFFF QR_HyperUpgradeFatigue  = 6576h
FFFFFFFF QR_BattleStatisticsHelp  = 6578h
FFFFFFFF QR_GrowthHelperInfo  = 657Ch
FFFFFFFF QR_GuildPoint    = 659Bh
FFFFFFFF QR_GuildJoinReqeust  = 659Fh
FFFFFFFF QR_MesoExchange_Info  = 66EEh
FFFFFFFF QR_BUYLIMIT_RESET  = 66EFh
FFFFFFFF QR_MesoExchange_TradedPrice  = 66F1h
FFFFFFFF QR_Hyper_Upgrade_Event  = 66FAh
FFFFFFFF QR_DayOfMemoInGameSendCount  = 6707h
FFFFFFFF QR_NaviFlying    = 6736h
FFFFFFFF QR_NaviFlyingNPC  = 6756h
FFFFFFFF QR_PremiumGuide  = 675Ah
FFFFFFFF QR_SoulCollection  = 6763h
FFFFFFFF QR_CoordinationContest_Info  = 6776h
FFFFFFFF QR_Soul_Dungeon_Init  = 677Bh
FFFFFFFF QR_CoordinationContest_Reg_PreEntry  = 6781h
FFFFFFFF QR_CoordinationContest_Reward_PreEntry  = 6782h
FFFFFFFF QR_CoordinationContest_Reward_PreVote  = 6783h
FFFFFFFF QR_CoordinationContest_Reward_Vote  = 6784h
FFFFFFFF QR_CoordinationContest_Reward_Evaluate  = 678Ch
FFFFFFFF QR_SoulEffect    = 67A7h
FFFFFFFF QR_Mannequin_0   = 67B0h
FFFFFFFF QR_Mannequin_1   = 67B1h
FFFFFFFF QR_PET_EVOLUTION  = 67B5h
FFFFFFFF QR_MesoExchange_TaxInfo  = 67D3h
FFFFFFFF QR_RenameCharacterLog  = 67D4h
FFFFFFFF QR_PigStick_MiniGame_Invite  = 67DBh
FFFFFFFF QR_Soul_Dungeon_Result_And_Rank  = 67E8h
FFFFFFFF QR_Soul_Dungeon_Mvp  = 67ECh
FFFFFFFF QR_RenameCharacterNewLog  = 67EEh
FFFFFFFF QR_MesoExchange_Discount_TaxRate_Buy1  = 68B0h
FFFFFFFF QR_MesoExchange_Discount_TaxRate_Buy10  = 68B9h
FFFFFFFF QR_MesoExchange_Discount_TaxPrice_Buy1  = 68BAh
FFFFFFFF QR_MesoExchange_Discount_TaxPrice_Buy10  = 68C3h
FFFFFFFF QR_MesoExchange_Discount_TaxRate_Sell1  = 68C4h
FFFFFFFF QR_MesoExchange_Discount_TaxRate_Sell10  = 68CDh
FFFFFFFF QR_MesoExchange_Discount_TaxPrice_Sell1  = 68CEh
FFFFFFFF QR_MesoExchange_Discount_TaxPrice_Sell10  = 68D7h
FFFFFFFF QR_MesoExchange_Bonus_Meso1  = 68D8h
FFFFFFFF QR_MesoExchange_Bonus_Meso10  = 68E1h
FFFFFFFF QR_MesoExchange_Bonus_MaplePoint1  = 68E2h
FFFFFFFF QR_MesoExchange_Bonus_MaplePoint10  = 68EBh
FFFFFFFF QR_MentoringMatchedList1  = 691Ah
FFFFFFFF QR_MentoringMatchedList2  = 691Bh
FFFFFFFF QR_ActivePremiumDamageSkin  = 698Eh
FFFFFFFF QR_HuntingMaster  = 72D8h
FFFFFFFF QR_HontaleSlayer  = 733Dh
FFFFFFFF QR_BabyBossSlayer  = 733Eh
FFFFFFFF QR_MedalReissue_Count  = 74FDh
FFFFFFFF QR_DailyRandomQuest  = 7546h
FFFFFFFF QR_RootabyssReturnMap  = 754Ch
FFFFFFFF QR_Rootabyss     = 754Dh
FFFFFFFF QR_GhostParkClearCheck  = 75F8h
FFFFFFFF QR_New_Krease_Partner_1  = 7963h
FFFFFFFF QR_New_Krease_Partner_2  = 7965h
FFFFFFFF QR_New_Krease_Partner_3  = 7966h
FFFFFFFF QR_New_Krease_Partner_4  = 7967h
FFFFFFFF QR_New_Krease_Partner_5  = 7968h
FFFFFFFF QR_Cygnus_Clear  = 79DBh
FFFFFFFF QR_FPSMode_Success  = 7A7Fh
FFFFFFFF QR_AdventureJournal_Start_Adventurer  = 7DF0h
FFFFFFFF QR_InvasionSupport_AttackSay  = 7EA4h
FFFFFFFF QR_InvasionSupport_AttackWeapon  = 7EA5h
FFFFFFFF QR_InvasionSupport_AttackEnd  = 7EA6h
FFFFFFFF QR_InvasionSupport_BossKiller  = 7EA7h
FFFFFFFF QR_InvasionSupport_BestAttacker  = 7EA8h
FFFFFFFF QR_InvasionSupport_Count  = 7EA9h
FFFFFFFF QR_Hekaton_Reward_Alarm  = 7F20h
FFFFFFFF QR_ItemLevelPoint  = 7F23h
FFFFFFFF QR_Hekaton_Reward  = 7F24h
FFFFFFFF QR_Hekaton_Entrance  = 7F26h
FFFFFFFF QR_Capture_the_flag_lap  = 7F45h
FFFFFFFF QR_DimensionLibrary  = 7F58h
FFFFFFFF QR_Spinoff_Prologue  = 7FBCh
FFFFFFFF QR_Spinoff_Chapter1  = 7FBDh
FFFFFFFF QR_Spinoff_Chapter2  = 7FBEh
FFFFFFFF QR_Spinoff_Chapter3  = 7FBFh
FFFFFFFF QR_Spinoff_Chapter4  = 7FC0h
FFFFFFFF QR_Spinoff_Chapter5  = 7FC1h
FFFFFFFF QR_Spinoff_NewIcon  = 7FCFh
FFFFFFFF QR_Spinoff_Dungeon_First_Direction  = 814Ch
FFFFFFFF QR_Blockbuster_BlackHeaven  = 8160h
FFFFFFFF QR_Blockbuster_Alarm  = 8169h
FFFFFFFF QR_Blockbuster_Progress  = 816Ah
FFFFFFFF QR_Blockbuster_BlackHeaven_SSFS  = 819Ch
FFFFFFFF QR_MazeInfo_BlackHeaven  = 81BDh
FFFFFFFF QR_MazeRecord_BlackHeaven  = 81BEh
FFFFFFFF QR_MazeArea_BackHeaven  = 81BFh
FFFFFFFF QR_BlackHeaven_Partner_NineHeart_1  = 81C9h
FFFFFFFF QR_BlackHeaven_Partner_NineHeart_2  = 81CAh
FFFFFFFF QR_BlackHeaven_Partner_NineHeart_3  = 81CBh
FFFFFFFF QR_BlackHeaven_Partner_NineHeart_4  = 81CCh
FFFFFFFF QR_BlackHeaven_Partner_Sigmund  = 81E0h
FFFFFFFF QR_BlackHeaven_Partner_Helena  = 81E1h
FFFFFFFF QR_Blockbuster_BlackHeaven_MGC  = 8224h
FFFFFFFF QR_Spinoff_Chapter6  = 82FAh
FFFFFFFF QR_URUS_SKILL    = 830Fh
FFFFFFFF QR_URUS_RETURN_MAP  = 8311h
FFFFFFFF QR_Urus_Result_TimeAssist  = 8312h
FFFFFFFF QR_Urus_Result_Damage  = 8313h
FFFFFFFF QR_Urus_Result_ScoreGrade  = 8314h
FFFFFFFF QR_Urus_Result_Rank1  = 8315h
FFFFFFFF QR_Urus_Result_Rank2  = 8316h
FFFFFFFF QR_Urus_Result_Rank3  = 8317h
FFFFFFFF QR_Urus_Result_Rank4  = 8318h
FFFFFFFF QR_Urus_Result_KingList  = 8319h
FFFFFFFF QR_Urus_Medal_Info  = 831Ah
FFFFFFFF QR_Urus_Penalty  = 831Dh
FFFFFFFF QR_Urus_Pre      = 831Dh
FFFFFFFF QR_Urus_More_LogInfo  = 8336h
FFFFFFFF QR_Urus_Team_HP  = 8408h
FFFFFFFF QR_Urus_Team_CatchSuccess  = 8409h
FFFFFFFF QR_Urus_Team_CatchFail  = 840Ah
FFFFFFFF QR_Urus_Team_Rescue  = 840Bh
FFFFFFFF QR_Urus_Team_TouchMe  = 840Ch
FFFFFFFF QR_Urus_Team_GrabSuccess  = 840Dh
FFFFFFFF QR_Urus_Team_GrabFail  = 840Eh
FFFFFFFF QR_Urus_Team_Clear  = 840Fh
FFFFFFFF QR_Urus_Team_PartArm  = 8410h
FFFFFFFF QR_Urus_Team_PartShoulder  = 8411h
FFFFFFFF QR_Urus_Team_PartHead  = 8412h
FFFFFFFF QR_Urus_Team_DamageTaken  = 8413h
FFFFFFFF QR_Urus_Team_HitAss  = 8414h
FFFFFFFF QR_Urus_Team_HitEnv  = 8415h
FFFFFFFF QR_Urus_User_CatchCount  = 843Ah
FFFFFFFF QR_Urus_User_CatchRate  = 843Bh
FFFFFFFF QR_Urus_User_RescueCount  = 843Ch
FFFFFFFF QR_Urus_User_RescueRate  = 843Dh
FFFFFFFF QR_Urus_User_TouchMe  = 843Eh
FFFFFFFF QR_Urus_User_DealRate  = 843Fh
FFFFFFFF QR_Urus_User_Heal  = 8440h
FFFFFFFF QR_Urus_User_Finish  = 8441h
FFFFFFFF QR_Urus_User_HitEnv  = 8442h
FFFFFFFF QR_Urus_User_DamateTaken  = 8443h
FFFFFFFF QR_SwitchRP_LastIndex  = 846Ch
FFFFFFFF QR_SwitchRP_ACT1  = 846Dh
FFFFFFFF QR_SwitchRP_ACT2  = 846Eh
FFFFFFFF QR_SwitchRP_ACT3  = 846Fh
FFFFFFFF QR_SwitchRP_ACT4  = 8470h
FFFFFFFF QR_HofM_Alarm    = 847Dh
FFFFFFFF QR_PlatformerStage_EnterInfo  = 86C6h
FFFFFFFF QR_Hidden_Tutorial_Teleport  = 9855h
FFFFFFFF QR_UserResearchMap  = 9858h
FFFFFFFF QR_First_TearOfGoddess  = 9CB0h
FFFFFFFF QR_Second_TearOfGoddess  = 9D12h
FFFFFFFF QR_Third_TearOfGoddess  = 9D76h
FFFFFFFF QR_Last_TearOfGoddess  = 9F01h
FFFFFFFF QR_Zero_ACT_START  = 9FC4h
FFFFFFFF QR_Zero_ACT_FREE  = 0A014h
FFFFFFFF QR_Zero_Lucky_Equip  = 0A3B3h
FFFFFFFF QR_ZeroTagTutorial  = 0A3C9h
FFFFFFFF QR_HazyStoneTimer  = 0A410h
FFFFFFFF QR_ABYSSTOWER_FLOOR  = 0A412h
FFFFFFFF QR_TheSeedTowerRanking  = 0A412h
FFFFFFFF QR_ABYSSTOWER_POINT  = 0A413h
FFFFFFFF QR_SeedTowerRankingSave  = 0A476h
FFFFFFFF QR_SeedTowerWeekSave  = 0A47Ah
FFFFFFFF QR_StarPlanet_HundredRps  = 0AA50h
FFFFFFFF QR_StarPlanet_HundredRps_JoinUser  = 0AA51h
FFFFFFFF QR_StarPlanet_HundredBingo  = 0AA52h
FFFFFFFF QR_StarPlanet_HundredBingo_JoinUser  = 0AA53h
FFFFFFFF QR_StarPlanet_OneCard_Customizing  = 0AA54h
FFFFFFFF QR_StarPlanet_TypingGame_Customizing  = 0AA55h
FFFFFFFF QR_StarPlanet_TABG_Customizing  = 0AA56h
FFFFFFFF QR_StarPlanet_Yut_Customizing  = 0AA57h
FFFFFFFF QR_StarPlanet_TypingGameSolo_Customizing  = 0AA58h
FFFFFFFF QR_StarPlanet_Matching_ExceptUser1  = 0AA59h
FFFFFFFF QR_StarPlanet_Matching_ExceptUser2  = 0AA5Ah
FFFFFFFF QR_StarPlanet_Matching_LastMatching  = 0AA5Bh
FFFFFFFF QR_StarPlanet_WorldEvent_Reward  = 0AA62h
FFFFFFFF QR_StarPlanet_TypingGame  = 0AA65h
FFFFFFFF QR_StarPlanet_TypingGameSolo  = 0AA66h
FFFFFFFF QR_StarPlanet_TABGResult  = 0AA67h
FFFFFFFF QR_StarPlanet_YutResult  = 0AA68h
FFFFFFFF QR_StarPlanet_SuperYutResult  = 0AA69h
FFFFFFFF QR_StarPlanet_OneCard  = 0AA6Ah
FFFFFFFF QR_StarPlanet_OneCardResult  = 0AA6Bh
FFFFFFFF QR_StarPlanet_GSRPSGame  = 0AA6Ch
FFFFFFFF QR_StarPlanet_MiniGame  = 0AA6Dh
FFFFFFFF QR_StarPlanet_MiniGamePlay  = 0AA6Eh
FFFFFFFF QR_StarPlanet_Enter_ReturnMap  = 0AA74h
FFFFFFFF QR_StarPlanet_LastFieldID  = 0AA78h
FFFFFFFF QR_StarPlanet_OPGameScore  = 0AA7Ah
FFFFFFFF QR_StarPlanet_MiniGame_Rating_1  = 0AA7Bh
FFFFFFFF QR_StarPlanet_MiniGame_Rating_2  = 0AA7Ch
FFFFFFFF QR_StarPlanet_PointInfo  = 0AABEh
FFFFFFFF QR_StarPlanet_UI  = 0AABFh
FFFFFFFF QR_StarPlanet_RewardRecv  = 0AACCh
FFFFFFFF QR_StarPlanet_RewardInfo  = 0AACFh
FFFFFFFF QR_StarPlanet_MaxPoint  = 0AAD0h
FFFFFFFF QR_StarPlanet_HundredRps_PlayCount  = 0AAD9h
FFFFFFFF QR_StarPlanet_HundredBingo_PlayCount  = 0AADAh
FFFFFFFF QR_StarPlanet_RelaxExp  = 0AADCh
FFFFFFFF QR_StarPlanet_ExpBuff  = 0AADCh
FFFFFFFF QR_StarPlanet_Ranking  = 0AADEh
FFFFFFFF QR_StarPlanet_GradeUp_G03  = 0AAECh
FFFFFFFF QR_StarPlanet_GradeUp_G04  = 0AAEDh
FFFFFFFF QR_StarPlanet_GradeUp_G05  = 0AAEEh
FFFFFFFF QR_StarPlanet_GradeUp_G06  = 0AAEFh
FFFFFFFF QR_StarPlanet_GradeUp_G07  = 0AAF0h
FFFFFFFF QR_StarPlanet_GradeUp_G08  = 0AAF1h
FFFFFFFF QR_StarPlanet_GradeUp_G09  = 0AAF2h
FFFFFFFF QR_StarPlanet_GradeUp_G10  = 0AAF3h
FFFFFFFF QR_StarPlanet_GradeUp_G11  = 0AAF4h
FFFFFFFF QR_StarPlanet_ShiningStar  = 0AAF9h
FFFFFFFF QR_StarPlanet_DanceEndTime  = 0AAFFh
FFFFFFFF QR_StarPlanet_Omok_Record  = 0AB06h
FFFFFFFF QR_StarPlanet_Omok_CurrentRet  = 0AB07h
FFFFFFFF QR_StarPlanet_Attendance  = 0AB09h
FFFFFFFF QR_StarPlanet_WorldEventParticipant  = 0AB0Ah
FFFFFFFF QR_StarPlanet_BuffLog_Start  = 0AB0Eh
FFFFFFFF QR_StarPlanet_BuffLog_End  = 0AB17h
FFFFFFFF QR_StarPlanet_GroupDance  = 0AB2Dh
FFFFFFFF QR_StarPlanet_GroupDance_MaxSuccess  = 0AB36h
FFFFFFFF QR_StarPlanet_YutResultForTime  = 0AB39h
FFFFFFFF QR_StarPlanet_GSRPSGameForTime  = 0AB3Ah
FFFFFFFF QR_StarPlanet_TypingGameSoloForTime  = 0AB3Bh
FFFFFFFF QR_StarPlanet_TypingGameForTime  = 0AB3Ch
FFFFFFFF QR_StarPlanet_TABGResultForTime  = 0AB3Dh
FFFFFFFF QR_StarPlanet_OneCardResultForTime  = 0AB3Eh
FFFFFFFF QR_StarPlanet_SuperYutResultForTime  = 0AB3Fh
FFFFFFFF QR_BattlePvP_ResultForTime  = 0AB40h
FFFFFFFF QR_StarPlanet_SuperYutSkill  = 0AB4Dh
FFFFFFFF QR_BattlePvP_Result  = 0AB54h
FFFFFFFF QR_STARPLANET_PLAY_LOG  = 0B98Ch
FFFFFFFF QR_STARPLANET_ACT_LOG  = 0B98Dh
FFFFFFFF QR_STARPLANET_SOCIAL_LOG  = 0B98Eh
FFFFFFFF QR_STARPLANET_SYSTEM_LOG  = 0B98Fh
FFFFFFFF QR_YUT_DICE      = 0BA55h
FFFFFFFF QR_YUT_CATCH     = 0BA56h
FFFFFFFF QR_TABG_DICE     = 0BA5Ah
FFFFFFFF QR_TABG_BOSS_CELL  = 0BA5Bh
FFFFFFFF QR_ONECARD_DAMAGED  = 0BA5Fh
FFFFFFFF QR_ONECARD_LOG   = 0BA60h
FFFFFFFF QR_TYPINGGAME_LOG  = 0BA64h
FFFFFFFF QR_TYPINGGAME_SKILL  = 0BA65h
FFFFFFFF QR_BATTLEPVP_CHAR_SEL  = 0BA69h
FFFFFFFF QR_SUPER_YUT_DICE  = 0BA6Eh
FFFFFFFF QR_SUPER_YUT_CATCH  = 0BA6Fh
FFFFFFFF QR_SUPER_YUT_SKILL_YUT  = 0BA70h
FFFFFFFF QR_SUPER_YUT_SKILL_PIECE  = 0BA71h
FFFFFFFF QR_SUPER_YUT_NO_USE_SKILL  = 0BA72h
FFFFFFFF QR_SUPER_YUT_USE_ALLSKILL  = 0BA73h
FFFFFFFF QR_RandomMission  = 0BF68h
FFFFFFFF QR_RunnerGame    = 0D0C8h
FFFFFFFF
     */
    // old
    public static final int WILD_HUNTER_JAGUAR_STORAGE_ID = 23008;
    public static final int DIMENSION_LIBRARY = 32600;

    public static final int SILENT_CRUSADE_WANTED_TAB_1 = 1648;
    public static final int SILENT_CRUSADE_WANTED_TAB_2 = 1649;
    public static final int SILENT_CRUSADE_WANTED_TAB_3 = 1650;
    public static final int SILENT_CRUSADE_WANTED_TAB_4 = 1651;

    public static final int MEDAL_REISSUE_QUEST = 29949;

    public static final int EVAN_PROMOTED = 22130;
    public static final int EVAN_RIDING = 22402;

    public static final int MATRIX_SHARDS = 1477;

    public static String getWhStorageQuestValByTemplateID(int templateId) {
        if (templateId >= 9304000 && templateId <= 9304008) {
            return String.valueOf((templateId % 10) + 1);
        }
        return null;
    }
}
