# A Close Call - Start (3rd job adv for CoK)
sm.setPlayerAsSpeaker()
sm.sendNext("What kind of book can that be... Wow, the book is written by letters I have never seen before.")
sm.sendNext("But it still looks like something important. I should bring it back to Ereve.")
sm.sendNext("It's chilling.")
sm.setSpeakerID(1104302)
sm.sendSay("What's happening? Where are they appearing from? Try to snatch my book? No! I won't let the Black Wings take that!")
sm.warp(922030400, 0)
sm.startQuest(parentID)
sm.dispose()