# 21201 - [Job Adv] (Lv.30)   Aran
sm.setSpeakerID(1201002)
sm.sendNext("First you promise to defeat the Black Mage and make me a famous weapon, then you abandon me for hundreds of years, and now you're telling me you don't remember who I am? What the...?! Do you think I'll let you get away with that? You're the one who begged and pined for me!")
sm.setPlayerAsSpeaker()
sm.sendNext("I did tell #p1203000# to make a polearm for me if I could prove my worth.")
sm.setSpeakerID(1201002)
sm.sendNext("After all that begging, shouldn't you treat me with a little more love and respect? Ya know, a weapon like me's rare and a wonderful thing. I am the ultimate #p1201001# that can help you defeat the Black Mage. How could you ditch me for hundreds of years...")
sm.setPlayerAsSpeaker()
sm.sendNext("Hey, I never begged for you.")
sm.setSpeakerID(1201002)
sm.sendNext("What? You never begged for me? Ha! #p1203000# told me you got on your knees, begged for me in tears, and... Wait a sec. Aran! Did you just remember who I am?!")
sm.setPlayerAsSpeaker()
sm.sendNext("Maybe a little bit...")
sm.setSpeakerID(1201002)
sm.sendNext("Aran, it is you! *Sniff sniff* Wait, *ahem* I didn't get emotional, it's just allergies. I know the Black Mage has stripped you of your abilities so you probably don't even have the strength to lift me... but at least you remember me! I'm glad that your memory's starting to return.")
if sm.sendAskYesNo("Evn though you've lost your memory, you're still my master. You endured some very tough training in the past, and I'm sure your body still remembers the skills that got you through those hard times. Alright, I'll restore your abilities!"):
    sm.giveItem(1142130)
    sm.setJob(2110)
    sm.addSP(5)
    sm.completeQuest(parentID)
    sm.sendNext("Your level isn't what it used to be back in your glory days, so I can't restore all of your old abilities. But the few that I can restore should help you level up faster. Now hurry up and train so you can return to the old you.")
    sm.dispose()
else:
    sm.dispose()
