#23215 | True Awakening
sm.setSpeakerID(2450017)
if sm.sendAskYesNo("How's your training going, #h # good?"):
    sm.sendSayOkay("Really? Are you sure It's going well?")
    sm.dispose()
else:
    sm.setPlayerAsSpeaker()
    sm.sendNext("Mastema, I wanted to talk with you.")
    sm.setSpeakerID(2450017)
    sm.sendNext("(Eh? #h # wanted to speak to me? Glee!) Ah, yes? About what?")
    sm.setPlayerAsSpeaker()
    sm.sendNext("I would like to repeat my previous training.")
    sm.setSpeakerID(2450017)
    sm.sendNext("Previous training? Guess you've hit another wall, then. I don't think repeating that training is going to help, #h #...")
    sm.setPlayerAsSpeaker()
    sm.sendNext("I understand, but I seem to be out of options.")
    sm.setSpeakerID(2450017)
    sm.sendNext("Hm. Wait...wait! I've got an idea. Ohh, I've got a really good idea! You want to get back to your old power level, right, #h #? In that case you should practice against #h #! Or more specifically, #h # from the past.")
    sm.sendNext("Normally the Temple of Time is the only place where you can tinker with time, but I found another, #h #. Word is, there is something wrong with time in Ludibrium.")
    sm.sendNext("There's a place called #bPath of Time#k on Ludibrium's Clock Tower Bottom Floor. I can stabilize the Crack in Time so you can travel to where you need to go.")
    sm.sendNext("Yeah, I know I look funny like this, but this form allows me to move between dimensions. I'll meet you at the place... I'm taking the scenic route.")
    sm.sendNext("Entering the Crack of Time will shift you to a point in the past, but don't worry about messing things up. The way this works, your actions won't affect the future.")
    sm.startQuest(parentID)
    sm.warp(220050300, 2)
