sm.setPlayerAsSpeaker()
sm.sendNext("This is Maple World? Did I really... return? I never thought I'd see it again.")
sm.sendSay("I bet everyone is doing well. I'm off to see my friends!")

sm.setJob(2510)
sm.addSP(5, True)
sm.startQuest(parentID)
sm.completeQuest(parentID)
sm.addMaxHP(342)
sm.addMaxMP(665)